name: Multi Environments Deploy
on:
  # Triggers the workflow on push to matching branches
  workflow_dispatch:
    inputs:
      tenant1:
        description: 'tenan1'
        required: true
        default: true
        type: boolean
      tenant2:
        description: 'tenant2'
        required: true
        default: true
        type: boolean
  push:
    branches:
    - main  
env:
  duplo_host: https://included-ai.duplocloud.net 
  duplo_token: "${{ secrets.DUPLO_TOKEN }}"
  SERVICE_NAME: included
  TENANT_NAMES: "tenant1,tenant2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tenant1
        run: echo "tenant1"
        if: inputs.tenant1
      - name: tenant1
        run: echo "tenant2"
        if: inputs.tenant2