name: Rebase Dev with Master

on:
  push:
    branches:
      - main

jobs:
  rebase_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Rebase dev with main
      run: |
        git checkout development
        git pull origin main --rebase
        git push origin development
