name: SuccessFailConditions

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This step will fail" && exit 1
      - name: Step 2
        continue-on-error: true
        run: echo "This step will run even if Step 1 fails"
      - name: Step 3
        run: echo "This step will not run if Step 1 or Step 2 fails"
